### ISSUE TITLE
Default datetime format assumption

### ISSUE THREAD

**Issue by abhispra** [jborean93/psrpcore#20]
Hey Jordan,

_deserialize_datetime(psrpcore/types/_serializer.py - line 147) assumes a default format from PS as 
```
'YYYY-MM-DDTHH:MM-SS[.100's of nanoseconds]Z
```
In my setup, the response never contains the timezone information resulting in an unhandled exception in converting time data. Debug logs -

```
DEBUG:psrpcore._base:Unpacked fragment - OID: 4, FID: 0, Start: True, End: True, Length: 746
DEBUG:psrpcore._base:Processing PSRP Message - MessageType: PipelineOutput,  RPID: 5d6e20f4-31f4-4f22-a9a0-01979437e483,  PID: 722fa358-f3f4-4088-82c0-2fbf9f076936,  OID: 4, Type: default - '<Obj RefId="0"><TN RefId="0"><T>Microsoft.GroupPolicy.Gpo</T><T>System.Object</T></TN><ToString>Microsoft.GroupPolicy.Gpo</ToString><Props><G N="Id">2cb31817-de6e-4754-9468-fe305005ad50</G><S N="DisplayName">Test GPO</S><S N="Path">cn={2CB31817-DE6E-4754-9468-FE305005AD50},cn=policies,cn=system,DC=corp,DC=cmonk,DC=com</S><S N="Owner">CORP\Domain Admins</S><S N="DomainName">corp.cmonk.com</S><DT N="CreationTime">2022-12-08T04:54:33</DT><DT N="ModificationTime">2022-12-08T04:57:34</DT><S N="User">Microsoft.GroupPolicy.UserConfiguration</S><S N="Computer">Microsoft.GroupPolicy.ComputerConfiguration</S><S N="GpoStatus">AllSettingsEnabled</S><Nil N="WmiFilter" /><Nil N="Description" /></Props></Obj>'
ERROR:psrp._connection.wsman:WSMan listener encountered unhandled exception
Traceback (most recent call last):
  File "/home/abhispra/bazc/code/new-plugins/bazcli2/plugins/pshell/pshell-venv/lib/python3.8/site-packages/psrpcore/types/_serializer.py", line 199, in _deserialize_datetime
    dt = PSDateTime.strptime(datetime_str, "%Y-%m-%dT%H:%M:%S.%f%z")
  File "/home/abhispra/bazc/code/new-plugins/bazcli2/plugins/pshell/pshell-venv/lib/python3.8/site-packages/psrpcore/types/_primitive.py", line 451, in strptime
    return cls(super().strptime(date_string, format))
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-12-08T04:54:33' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abhispra/bazc/code/new-plugins/bazcli2/plugins/pshell/pshell-venv/lib/python3.8/site-packages/psrp/_connection/wsman.py", line 715, in _listen
    data_available = self.process_response(msg)
  File "/home/abhispra/bazc/code/new-plugins/bazcli2/plugins/pshell/pshell-venv/lib/python3.8/site-packages/psrp/_connection/connection.py", line 274, in process_response
    event = pool.next_event()
  File "/home/abhispra/bazc/code/new-plugins/bazcli2/plugins/pshell/pshell-venv/lib/python3.8/site-packages/psrpcore/_base.py", line 350, in next_event
    event = self._process_message(message)
  File "/home/abhispra/bazc/code/new-plugins/bazcli2/plugins/pshell/pshell-venv/lib/python3.8/site-packages/psrpcore/_base.py", line 452, in _process_message
    ps_object = deserialize(
  File "/home/abhispra/bazc/code/new-plugins/bazcli2/plugins/pshell/pshell-venv/lib/python3.8/site-packages/psrpcore/types/_serializer.py", line 123, in deserialize
    return _Serializer(cipher, **kwargs).deserialize(value)
  File "/home/abhispra/bazc/code/new-plugins/bazcli2/plugins/pshell/pshell-venv/lib/python3.8/site-packages/psrpcore/types/_serializer.py", line 989, in deserialize
    prop_value = self.deserialize(obj_property)
  File "/home/abhispra/bazc/code/new-plugins/bazcli2/plugins/pshell/pshell-venv/lib/python3.8/site-packages/psrpcore/types/_serializer.py", line 827, in deserialize
    return _deserialize_datetime(element_text)
  File "/home/abhispra/bazc/code/new-plugins/bazcli2/plugins/pshell/pshell-venv/lib/python3.8/site-packages/psrpcore/types/_serializer.py", line 202, in _deserialize_datetime
    dt = PSDateTime.strptime(datetime_str, "%Y-%m-%dT%H:%M:%S%z")
  File "/home/abhispra/bazc/code/new-plugins/bazcli2/plugins/pshell/pshell-venv/lib/python3.8/site-packages/psrpcore/types/_primitive.py", line 451, in strptime
```

A couple of questions - 
1. Shouldn't the format be queried from the current session before specifying the format to strptime?
2. I couldn't figure out a workaround to get past this exception. Changing the format strptime indeed works. Any suggestion to work around the issue?

Thank you for the great work you have been doing in maintaining both PS libraries. I would be happy to contribute if there is anything I can help with.

**Comment by jborean93** [comment]
That's interesting, the code does try and do strptime with the `%z` token but that's because the code is dding the offset manually if it's not present https://github.com/jborean93/psrpcore/blob/main/src/psrpcore/types/_serializer.py#L185-L202. I think I do see a problem in the code though where it's only converting the offset if present to the format Python expects or converting `Z` to `+0000` and not dealing with it being missing.

I can't say I've encountered this before but the fact you are seeing it means it does happen. When testing things locally I think this occurs when the DateTimeKind for a DateTime object is Unspecified, i.e.

* Utc -> `<DT>2022-12-18T07:17:10.01Z</DT>`
* Local -> `<DT>2022-12-18T07:17:10.01+10:00</DT>`
* Unspecified -> `<DT>2022-12-18T07:17:10.01</DT>`

**Comment by jborean93** [comment]
Sorry I didn't answer these

> Shouldn't the format be queried from the current session before specifying the format to strptime?

The format is based on [MS-PSRP Date/Time](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-psrp/a3b75b8d-ad7e-4649-bb82-cfa70f54fb8c)  which is very scant on the details  but essentially it's the ISO 8601 format of a datetime string. The problem is my code doesn't handle the `Unspecified` DateTimeKind format where the timezone is omitted from the string when it should.

> I couldn't figure out a workaround to get past this exception. Changing the format strptime indeed works. Any suggestion to work around the issue?

The only 2 workarounds is the change the code to handle it or make sure that a DateTime with a Kind of Unspecified is not returned back to be deserialized.

**Comment by jborean93** [comment]
PR that fixes this issue https://github.com/jborean93/psrpcore/pull/21.

Looks like I was also serializing Python datetime objects wrong. I was incorrectly adding `Z` to signify that it was a UTC datetime rather than omitting the time zone specified to keep it unspecified when no tzinfo was present.

**Comment by abhispra** [comment]
Thank you so much! BTW, super impressed by your tenacity in dealing with the ambiguities and challenges in PwSh. I couldn't find any other python library that exposes this capability over PwSh.

**Comment by jborean93** [comment]
You're welcome, issues like these are fantastic for finding these problems and fixing these edge cases so thanks for reporting it.
